# Generated by Django 4.2 on 2023-04-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iLVu2JournalApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="promptresponse", name="Prompt_Category",),
        migrations.AddField(
            model_name="promptcategory",
            name="category_img",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="UserPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_text", models.CharField(max_length=200)),
                (
                    "Prompt_Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iLVu2JournalApp.promptcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SitePrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_text", models.CharField(max_length=200)),
                (
                    "Prompt_Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iLVu2JournalApp.promptcategory",
                    ),
                ),
            ],
        ),
    ]
