# Generated by Django 4.2 on 2023-04-18 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iLVu2JournalApp", "0002_remove_promptresponse_prompt_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("mood_description", models.TextField(max_length=200)),
                ("mood_response", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="JournalTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "Prompt_Response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="iLVu2JournalApp.promptresponse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "App_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Journal_Tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="iLVu2JournalApp.journaltracker",
                    ),
                ),
                (
                    "Mood_Tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="iLVu2JournalApp.moodtracker",
                    ),
                ),
            ],
        ),
    ]
