# Generated by Django 4.2 on 2023-04-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iLVu2JournalApp", "0003_moodtracker_journaltracker_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
