# Generated by Django 4.2 on 2023-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iLVu2JournalApp", "0004_calendar_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
