# Generated by Django 4.2 on 2023-04-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iLVu2JournalApp", "0005_alter_calendar_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptresponse",
            name="prompt_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="iLVu2JournalApp.promptcategory",
            ),
        ),
    ]
