# Generated by Django 4.2 on 2023-04-18 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iLVu2JournalApp", "0006_alter_promptresponse_prompt_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="promptresponse", name="prompt_type",),
        migrations.AddField(
            model_name="promptresponse",
            name="Site_Prompt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="iLVu2JournalApp.siteprompt",
            ),
        ),
        migrations.AddField(
            model_name="promptresponse",
            name="User_Prompt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="iLVu2JournalApp.userprompt",
            ),
        ),
    ]
