# Generated by Django 4.2 on 2023-04-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iLVu2JournalApp", "0008_alter_calendar_journal_tracker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journaltracker",
            name="Prompt_Response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="iLVu2JournalApp.promptresponse",
            ),
        ),
    ]
