# Generated by Django 4.2 on 2023-04-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iLVu2JournalApp", "0009_alter_journaltracker_prompt_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="Journal_Tracker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="iLVu2JournalApp.journaltracker",
            ),
        ),
        migrations.AlterField(
            model_name="calendar",
            name="Mood_Tracker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="iLVu2JournalApp.moodtracker",
            ),
        ),
    ]
