# Generated by Django 4.2 on 2023-04-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iLVu2JournalApp", "0010_alter_calendar_journal_tracker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journaltracker",
            name="is_complete",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="moodtracker",
            name="is_complete",
            field=models.BooleanField(default=True),
        ),
    ]
