# Generated by Django 4.2 on 2023-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iLVu2JournalApp", "0011_alter_journaltracker_is_complete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
