# Generated by Django 4.2 on 2023-04-25 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iLVu2JournalApp", "0013_promptresponse_app_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodtracker",
            name="App_User",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
