# Generated by Django 4.2 on 2023-04-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iLVu2JournalApp", "0017_alter_moodtracker_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="moodtracker", name="date",),
    ]
