# Generated by Django 4.2 on 2023-04-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iLVu2JournalApp", "0019_moodtracker_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodtracker", name="date", field=models.DateField(null=True),
        ),
    ]
