# Generated by Django 4.2 on 2023-04-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iLVu2JournalApp", "0023_remove_moodtracker_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodtracker",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
